maxDefinitionListSize: 4
initial:
  load:
    word: home

oxford:
  service:
    api.id: ${OXFORD_API_ID}
    app.key: ${OXFORD_APP_KEY}
    definitions.service.endpoint: https://od-api.oxforddictionaries.com/api/v1/entries/en/X
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/admin
      database: english_cards