maxDefinitionSentencesList: 6
maxDefinitionSynonymsList: 6
maxDefinitionListSize: 4
initial:
  load:
    word: home

oxford:
  service:
    api.id: 
    app.key: 
    definitions.service.endpoint: https://od-api.oxforddictionaries.com/api/v1/entries/en/X
    synonyms.service.endpoint: https://od-api.oxforddictionaries.com/api/v1/entries/en/X/synonyms
    sentences.service.endpoint: https://od-api.oxforddictionaries.com/api/v1/entries/en/X/sentences

client:
  service:
    key: cecadbd7-e07c-48b2-b11d-038f7aaab4f6
    url: api/v1/clients
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/admin
      database: english_cards
  jpa:
    hibernate:
      ddl-auto: update
urls:
  skip:
    host:
      validation: api/v1/clients,api/v1/users/auth      