oxford:
  service:
    api.id: ${OXFORD_API_ID}
    app.key: ${OXFORD_API_KEY}
    definitions.service.endpoint: https://od-api.oxforddictionaries.com:443/api/v1/entries/en/X/definitions
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/admin
      database: test