endpoints:
  enabled: true
  sensitive: false

spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.HSQLDialect
    database: HSQL
  datasource:
    driverClassName: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:test
    username: sa
      
de.flapdoodle.embed: de.flapdoodle.embed.mongo
  