oxford.service.ap.id: 
oxford.service.ap.key:

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/english_cards
    username: postgres
    password: initdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update