oxford.service.ap.id:
oxford.service.ap.key:

# configure eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true

# custom attribute for the actuator info endpoint
info:
  app:
    name: english-cards-service

# give the application a name
spring:
  application:
    name: english-cards-service
  datasource:
    url: jdbc:postgresql://localhost:5432/english_cards
    username: postgres
    password: initdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

# disable actuagor security for endpoints
management:
  security:
    enabled: false